### ISSUE TITLE
Plans to Provide Wrapper Library?

### ISSUE THREAD

**Issue by blaskovicz** [adafruit/Adafruit-TB6612-Motor-Driver-Breakout-PCB#1]
Hello and thank you for continuing to provide an excellent platform and hardware!

Are there any plans to add a Adafruit_TB6612.h wrapper library and examples similar to other Adafruit breakouts?

There is one for the Sparkfun board, so this would surely be useful:
https://github.com/sparkfun/SparkFun_TB6612FNG_Arduino_Library/blob/master/src/SparkFun_TB6612.h

Thanks!

**Comment by ladyada** [comment]
hi please use that library - it will work great  :)

**Comment by blaskovicz** [comment]
I'll take that as a "no" :)
